name: portfolio
description: Eunice QA Portfolio
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  url_launcher: ^6.2.1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  http: ^1.1.0
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
    web:
      generate: true
      image_path: "assets/images/lego.png"
      background_color: "#0175C2"
      theme_color: "#0175C2"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/cv/Eunice Bukola Ogunshola.pdf

  fonts:
    - family: Lastica
      fonts:
        - asset: assets/fonts/lastica.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
#        - asset: assets/fonts/Poppins-Bold.ttf
#            weight: 700
#        - asset: assets/fonts/Poppins-Medium.ttf
#                weight: 500

#    - family: Shantel
#      fonts:
#        - asset: assets/fonts/sans.ttf
